import type { AtticManifest, AtticTriggerManifest } from "../core/types.js";

import { quoteIdentifier, quoteLiteral, quoteQualifiedName } from "./sql-escaping.js";

function renderTrigger(target: AtticTriggerManifest, namespace: string): string {
  const table = quoteQualifiedName(target.schema, target.table);
  const name = quoteIdentifier(target.name);
  const argumentsSql = [namespace, ...target.tags].map(quoteLiteral).join(", ");

  return [
    `DROP TRIGGER IF EXISTS ${name} ON ${table};`,
    `CREATE TRIGGER ${name}`,
    `AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON ${table}`,
    "FOR EACH STATEMENT",
    `EXECUTE FUNCTION attic.capture_statement(${argumentsSql});`,
  ].join("\n");
}

const SETUP_SQL = `-- Core metadata and durable invalidation state
CREATE SCHEMA IF NOT EXISTS attic;

CREATE TABLE IF NOT EXISTS attic.installation (
  namespace text PRIMARY KEY,
  manifest_hash text NOT NULL CHECK (length(manifest_hash) = 64),
  sql_abi_version integer NOT NULL CHECK (sql_abi_version > 0),
  installed_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

-- Existing pre-ABI installations are temporarily nullable until metadata finalization.
ALTER TABLE attic.installation
  ADD COLUMN IF NOT EXISTS sql_abi_version integer;

CREATE TABLE IF NOT EXISTS attic.tag_state (
  namespace text NOT NULL,
  tag text NOT NULL,
  generation bigint NOT NULL DEFAULT 0 CHECK (generation >= 0),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (namespace, tag)
);

CREATE TABLE IF NOT EXISTS attic.outbox (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  namespace text NOT NULL,
  tag text NOT NULL,
  generation bigint NOT NULL CHECK (generation > 0),
  request_id uuid,
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  available_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  locked_by uuid,
  locked_until timestamptz,
  last_error text,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  UNIQUE (namespace, tag, generation)
);

CREATE INDEX IF NOT EXISTS outbox_claim_idx
  ON attic.outbox (namespace, available_at, locked_until, id);
CREATE INDEX IF NOT EXISTS outbox_request_idx
  ON attic.outbox (namespace, request_id, id)
  WHERE request_id IS NOT NULL;

-- Invalid or absent transaction-local request IDs are treated as external writes.
CREATE OR REPLACE FUNCTION attic.current_request_id()
RETURNS uuid
LANGUAGE plpgsql
STABLE
AS $attic$
DECLARE
  value text := current_setting('attic.request_id', true);
BEGIN
  IF value IS NULL OR value = '' THEN
    RETURN NULL;
  END IF;

  BEGIN
    RETURN value::uuid;
  EXCEPTION WHEN invalid_text_representation THEN
    RETURN NULL;
  END;
END;
$attic$;

-- Drop only capture triggers whose first argument matches one Attic namespace.
CREATE OR REPLACE FUNCTION attic.drop_namespace_triggers(p_namespace text)
RETURNS integer
LANGUAGE plpgsql
VOLATILE
AS $attic$
DECLARE
  existing record;
  dropped integer := 0;
BEGIN
  IF p_namespace IS NULL OR btrim(p_namespace) = '' THEN
    RAISE EXCEPTION 'Attic namespace must not be empty';
  END IF;

  FOR existing IN
    SELECT trg.tgname,
           rel_schema.nspname AS schema_name,
           rel.relname AS table_name
      FROM pg_catalog.pg_trigger AS trg
      JOIN pg_catalog.pg_proc AS fn ON fn.oid = trg.tgfoid
      JOIN pg_catalog.pg_namespace AS fn_schema ON fn_schema.oid = fn.pronamespace
      JOIN pg_catalog.pg_class AS rel ON rel.oid = trg.tgrelid
      JOIN pg_catalog.pg_namespace AS rel_schema ON rel_schema.oid = rel.relnamespace
     WHERE NOT trg.tgisinternal
       AND fn_schema.nspname = 'attic'
       AND fn.proname = 'capture_statement'
       AND substring(
             trg.tgargs
             FROM 1
             FOR position(decode('00', 'hex') IN trg.tgargs) - 1
           ) = convert_to(p_namespace, 'UTF8')
  LOOP
    EXECUTE format(
      'DROP TRIGGER %I ON %I.%I',
      existing.tgname,
      existing.schema_name,
      existing.table_name
    );
    dropped := dropped + 1;
  END LOOP;

  RETURN dropped;
END;
$attic$;

-- Explicitly retire one old namespace without affecting any other installation.
CREATE OR REPLACE FUNCTION attic.retire_namespace(p_namespace text)
RETURNS void
LANGUAGE plpgsql
VOLATILE
AS $attic$
BEGIN
  IF EXISTS (SELECT 1 FROM attic.outbox WHERE namespace = p_namespace) THEN
    RAISE EXCEPTION 'Cannot retire Attic namespace % while its outbox is not empty', p_namespace;
  END IF;

  PERFORM attic.drop_namespace_triggers(p_namespace);

  -- Trigger DDL holds table locks. Recheck to catch a writer that committed while
  -- retirement was waiting for those locks; an exception restores dropped triggers.
  IF EXISTS (SELECT 1 FROM attic.outbox WHERE namespace = p_namespace) THEN
    RAISE EXCEPTION 'Cannot retire Attic namespace % because a concurrent write enqueued an event', p_namespace;
  END IF;

  DELETE FROM attic.tag_state WHERE namespace = p_namespace;
  DELETE FROM attic.installation WHERE namespace = p_namespace;
END;
$attic$;

-- Increment each tag and persist its outbox event in the caller's transaction.
CREATE OR REPLACE FUNCTION attic.enqueue_tags(
  p_namespace text,
  p_tags text[],
  p_request_id uuid DEFAULT NULL
)
RETURNS TABLE (
  id bigint,
  namespace text,
  tag text,
  generation bigint,
  request_id uuid,
  attempts integer
)
LANGUAGE plpgsql
VOLATILE
AS $attic$
DECLARE
  current_tag text;
  next_generation bigint;
  next_id bigint;
BEGIN
  IF p_namespace IS NULL OR btrim(p_namespace) = '' THEN
    RAISE EXCEPTION 'Attic namespace must not be empty';
  END IF;

  FOR current_tag IN
    SELECT DISTINCT item.tag
      FROM unnest(COALESCE(p_tags, ARRAY[]::text[])) AS item(tag)
     WHERE item.tag IS NOT NULL AND item.tag <> ''
     ORDER BY item.tag
  LOOP
    INSERT INTO attic.tag_state AS state (namespace, tag, generation, updated_at)
    VALUES (p_namespace, current_tag, 1, clock_timestamp())
    ON CONFLICT ON CONSTRAINT tag_state_pkey DO UPDATE
      SET generation = state.generation + 1,
          updated_at = clock_timestamp()
    RETURNING state.generation INTO next_generation;

    INSERT INTO attic.outbox AS event (
      namespace,
      tag,
      generation,
      request_id,
      attempts,
      available_at,
      created_at
    )
    VALUES (
      p_namespace,
      current_tag,
      next_generation,
      p_request_id,
      0,
      clock_timestamp(),
      clock_timestamp()
    )
    RETURNING event.id INTO next_id;

    id := next_id;
    namespace := p_namespace;
    tag := current_tag;
    generation := next_generation;
    request_id := p_request_id;
    attempts := 0;
    RETURN NEXT;
  END LOOP;
END;
$attic$;

-- Optional function API for dedicated workers; direct SKIP LOCKED SQL is equivalent.
CREATE OR REPLACE FUNCTION attic.claim_outbox(
  p_namespace text,
  p_worker_id uuid,
  p_batch_size integer DEFAULT 100,
  p_lease_ms integer DEFAULT 30000
)
RETURNS TABLE (
  id bigint,
  namespace text,
  tag text,
  generation bigint,
  request_id uuid,
  attempts integer
)
LANGUAGE sql
VOLATILE
AS $attic$
  WITH candidates AS (
    SELECT queued.id
      FROM attic.outbox AS queued
     WHERE queued.namespace = p_namespace
       AND queued.available_at <= clock_timestamp()
       AND (queued.locked_until IS NULL OR queued.locked_until < clock_timestamp())
     ORDER BY queued.id
     LIMIT LEAST(GREATEST(COALESCE(p_batch_size, 100), 1), 10000)
     FOR UPDATE SKIP LOCKED
  )
  UPDATE attic.outbox AS event
     SET locked_by = p_worker_id,
         locked_until = clock_timestamp()
           + (LEAST(GREATEST(COALESCE(p_lease_ms, 30000), 1), 86400000)::double precision
             * interval '1 millisecond'),
         attempts = event.attempts + 1
    FROM candidates
   WHERE event.id = candidates.id
  RETURNING event.id,
            event.namespace,
            event.tag,
            event.generation,
            event.request_id,
            event.attempts;
$attic$;

CREATE OR REPLACE FUNCTION attic.ack_outbox(
  p_namespace text,
  p_worker_id uuid,
  p_ids bigint[]
)
RETURNS bigint
LANGUAGE plpgsql
VOLATILE
AS $attic$
DECLARE
  affected bigint;
BEGIN
  DELETE FROM attic.outbox AS event
   WHERE event.namespace = p_namespace
     AND event.id = ANY(COALESCE(p_ids, ARRAY[]::bigint[]))
     AND (p_worker_id IS NULL OR event.locked_by = p_worker_id OR event.locked_by IS NULL);
  GET DIAGNOSTICS affected = ROW_COUNT;
  RETURN affected;
END;
$attic$;

CREATE OR REPLACE FUNCTION attic.retry_outbox(
  p_namespace text,
  p_worker_id uuid,
  p_ids bigint[],
  p_backoff_ms integer,
  p_error text
)
RETURNS bigint
LANGUAGE plpgsql
VOLATILE
AS $attic$
DECLARE
  affected bigint;
BEGIN
  UPDATE attic.outbox AS event
     SET locked_by = NULL,
         locked_until = NULL,
         available_at = clock_timestamp()
           + (LEAST(GREATEST(COALESCE(p_backoff_ms, 0), 0), 86400000)::double precision
             * interval '1 millisecond'),
         last_error = left(COALESCE(p_error, 'Unknown worker error'), 2000)
   WHERE event.namespace = p_namespace
     AND event.id = ANY(COALESCE(p_ids, ARRAY[]::bigint[]))
     AND event.locked_by = p_worker_id;
  GET DIAGNOSTICS affected = ROW_COUNT;
  RETURN affected;
END;
$attic$;

-- One statement-level trigger can fan out to multiple logical model tags.
CREATE OR REPLACE FUNCTION attic.capture_statement()
RETURNS trigger
LANGUAGE plpgsql
VOLATILE
AS $attic$
DECLARE
  tags text[] := ARRAY[]::text[];
  argument_index integer;
BEGIN
  IF TG_NARGS < 2 THEN
    RAISE EXCEPTION 'Attic trigger % requires a namespace and at least one tag', TG_NAME;
  END IF;

  FOR argument_index IN 1..(TG_NARGS - 1) LOOP
    tags := array_append(tags, TG_ARGV[argument_index]);
  END LOOP;

  PERFORM attic.enqueue_tags(TG_ARGV[0], tags, attic.current_request_id());
  RETURN NULL;
END;
$attic$;`;

/** Renders an idempotent PostgreSQL migration for an Attic manifest. */
export function renderMigrationSql(manifest: AtticManifest): string {
  const metadataSql = `-- Attic SQL functions are shared by every namespace in this database.
-- Advancing the ABI invalidates older runtimes for every installed namespace.
UPDATE attic.installation
   SET sql_abi_version = ${String(manifest.sqlAbiVersion)},
       updated_at = clock_timestamp()
 WHERE sql_abi_version IS DISTINCT FROM ${String(manifest.sqlAbiVersion)};

ALTER TABLE attic.installation
  ALTER COLUMN sql_abi_version SET NOT NULL;

INSERT INTO attic.installation AS installation (
  namespace,
  manifest_hash,
  sql_abi_version,
  installed_at,
  updated_at
)
VALUES (
  ${quoteLiteral(manifest.namespace)},
  ${quoteLiteral(manifest.schemaChecksum)},
  ${String(manifest.sqlAbiVersion)},
  clock_timestamp(),
  clock_timestamp()
)
ON CONFLICT (namespace) DO UPDATE
  SET manifest_hash = EXCLUDED.manifest_hash,
      sql_abi_version = EXCLUDED.sql_abi_version,
      updated_at = clock_timestamp();`;
  const triggers = manifest.triggers.map((target) => renderTrigger(target, manifest.namespace));
  const cleanupSql = `-- Remove this namespace's previous trigger set, including triggers left by table renames.
SELECT attic.drop_namespace_triggers(${quoteLiteral(manifest.namespace)});`;

  return [
    "-- Generated by attic-generator. Review and apply with Prisma Migrate.",
    "-- PostgreSQL is the source of truth; these objects record durable cache invalidations.",
    "",
    "BEGIN;",
    "",
    SETUP_SQL,
    "",
    cleanupSql,
    "",
    "-- Model and implicit many-to-many table triggers.",
    ...triggers.flatMap((trigger) => [trigger, ""]),
    "-- Record the manifest only after every database object was installed successfully.",
    metadataSql,
    "",
    "COMMIT;",
    "",
  ].join("\n");
}
